version: "3"

services:

   orange-database:
      image: leovs09/orange-database:0.1.1
      container_name: orange-database
      user: root
      ports:
         - 8765:8765
      volumes:
         - .:/ws/.
      env_file:
         - ./.env-list
      depends_on:
        - db
#        - redis
      links:
        - db
#        - redis

   db:
      image: postgres:11
      container_name: postgres
      ports:
         - 5432:5432
      env_file:
         - ./db.env

#   redis:
#      image: redis:5.0.4
#      container_name: redis
#      ports:
#         - 16379:6379
