version: "3"

services:

   orange-database:
      image: leovs09/orange-database:0.1.1
      container_name: orange-database
      ports:
         - 8765:8765
      volumes:
         - .:/ws/.
      env_file:
         - .env-list
      depends_on:
        - db
      links:
        - db

   db:
      image: postgres:11
      container_name: postgres
      ports:
         - 5432:5432
